# Generated by Django 2.2.6 on 2019-10-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cover_img',
            new_name='cover_img_url',
        ),
    ]
