# Generated by Django 2.2.6 on 2019-10-17 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='common.BaseModel')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('cover_img_url', models.URLField(blank=True, max_length=255)),
                ('original_post_url', models.URLField(max_length=512)),
                ('original_post_date', models.CharField(max_length=255)),
            ],
            bases=('common.basemodel',),
        ),
    ]
