# Generated by Django 2.2.6 on 2019-10-17 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('CNN', 'CNN'), ('ETP', 'ELTIEMPO'), ('EPS', 'ELPAIS'), ('NYT', 'NYT'), ('TWP', 'TWP')], default='CNN', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='original_post_url',
            field=models.URLField(max_length=512, unique=True),
        ),
    ]
