# Generated by Django 2.2.9 on 2020-02-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_auto_20200203_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('ETP', 'ELTIEMPO'), ('EPS', 'ELPAIS'), ('TWP', 'TWP')], max_length=3),
        ),
    ]
